In [1]:

import matplotlib.pyplot as plt
import numpy as np
import random
import math
from IPython.display import display, HTML
    

In [2]:

student_id = input("Enter your student id")
student_name = input("Enter your name")
print("STUDENT ID", student_id)
print("STUDENT NAME", student_name)


STUDENT ID 61375061h
STUDENT NAME 陳孟緯(Meng-Wei Chen)


<!-- <div class="question_frame"> --><!-- start of question_frame -->



<h1>Integral Image</h1>
<div class="question_body">

<p> Given is the following grayscale image of size 5x7.</p>
<div style="text-align:center;display:block">

<table " >

<tbody>

<tr>

<td>
122
</td>

<td>
142
</td>

<td>
242
</td>

<td>
57
</td>

<td>
203
</td>

<td>
232
</td>

<td>
30
</td>

</tr>

<tr>

<td>
141
</td>

<td>
5
</td>

<td>
79
</td>

<td>
106
</td>

<td>
138
</td>

<td>
65
</td>

<td>
230
</td>

</tr>

<tr>

<td>
34
</td>

<td>
149
</td>

<td>
203
</td>

<td>
129
</td>

<td>
141
</td>

<td>
34
</td>

<td>
240
</td>

</tr>

<tr>

<td>
214
</td>

<td>
220
</td>

<td>
243
</td>

<td>
150
</td>

<td>
250
</td>

<td>
140
</td>

<td>
246
</td>

</tr>

<tr>

<td>
252
</td>

<td>
9
</td>

<td>
154
</td>

<td>
68
</td>

<td>
239
</td>

<td>
26
</td>

<td>
10
</td>

</tr>

</tbody>
</table>

</div>

<p>The integral image <emph>s</emph> is defined by the following equation:</p>
<code>
s[x,y] = img[x,y] + s[x-1,y] + s[x,y-1] - s[x-1,y-1]
</code>

</div><!-- end of question_body -->



<div class="question_marks">
<span class="mark_num" style="text-align:right">10</span> marks
</div><!-- end of question_marks -->



<p>
Calculate the integral image for this input image and add it into the table below
</p>

<p>Enter the maximum value in the integral image that is less than 326 into the input
box.</p>

<p>Maximum value in the integral image that is less than 326 <input type="number"></input>


<p>Show your work and explain your answer in this cell. You can add additional markdown and code cells, if you want to after this cell.</p>

In [43]:
A = np.array([[122,142,242,57,203,232,30],
               [141,5,79,106,138,65,230],
               [34,149,203,129,141,34,240],
               [214,220,243,150,250,140,246],
               [252,9,154,65,239,26,10]]
)
img = np.zeros([7,9])
img[1:-1, 1:-1] = A
s = np.zeros([7,9])
# print(img)

for y in range(1,8):
    for x in range(1,6):
        s[x,y] = img[x,y] + s[x-1,y] + s[x,y-1] - s[x-1, y-1]
max_val_under_326 = s[s < 326].max()
print(s)
print(max_val_under_326)

[[   0.    0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.  122.  264.  506.  563.  766.  998. 1028.    0.]
 [   0.  263.  410.  731.  894. 1235. 1532. 1792.    0.]
 [   0.  297.  593. 1117. 1409. 1891. 2222. 2722.    0.]
 [   0.  511. 1027. 1794. 2236. 2968. 3439. 4185.    0.]
 [   0.  763. 1288. 2209. 2716. 3687. 4184. 4940.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.    0.]]
297.0


<!-- </div> --><!-- end of question_frame -->


In [42]:
import numpy as np

# 定義給定的影像矩陣
img = np.array([
    [122, 142, 242, 57, 203, 232, 30],
    [141, 5, 79, 106, 138, 65, 230],
    [34, 149, 203, 129, 141, 34, 240],
    [214, 220, 243, 150, 250, 140, 246],
    [252, 9, 154, 68, 239, 26, 10]
])

# 初始化積分影像矩陣，大小與 img 相同
s = np.zeros_like(img)

# 計算積分影像
for x in range(img.shape[0]):
    for y in range(img.shape[1]):
        s[x, y] = img[x, y]
        if x > 0:
            s[x, y] += s[x-1, y]
        if y > 0:
            s[x, y] += s[x, y-1]
        if x > 0 and y > 0:
            s[x, y] -= s[x-1, y-1]

# 找到小於 326 的最大值
max_val_under_326 = s[s < 326].max()

print("積分影像矩陣:")
print(s)
print("\n小於 326 的最大值:", max_val_under_326)


積分影像矩陣:
[[ 122  264  506  563  766  998 1028]
 [ 263  410  731  894 1235 1532 1792]
 [ 297  593 1117 1409 1891 2222 2722]
 [ 511 1027 1794 2236 2968 3439 4185]
 [ 763 1288 2209 2719 3690 4187 4943]]

小於 326 的最大值: 297


<!-- <div class="question_frame"> --><!-- start of question_frame -->



<h1>Horizontal Box Filter</h1>
<div class="question_body">

<p>
A horizontal box filter of size <code>8</code> is defined as follows:
</p>


<table " >

<tbody>

<tr>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

</tr>

<tr>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

</tr>

<tr>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

</tr>

<tr>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

<td>
1
</td>

</tr>

<tr>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

</tr>

<tr>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

</tr>

<tr>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

</tr>

<tr>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

<td>
0
</td>

</tr>

</tbody>
</table>


<p>The filter is applied to the pixel at offset x = 4, y = 4.</p>

<p>You can pad the image by adding rows and columns of 0 if needed to calculate the value of the box
filter along the edges of the image.</p>

</div><!-- end of question_body -->



<div class="question_marks">
<span class="mark_num" style="text-align:right">15</span> marks
</div><!-- end of question_marks -->



<p>
Calculate the output of the horizontal box filter for the image described above.
</p>

<p>Enter the maximum value in the box filter output that is less than 0 into the input
box.</p>

<p>Maximum value in the integral image that is less than 0 <input type="number"></input>


<p>Show your work and explain your answer in this cell. You can add additional markdown and code cells, if you want to after this cell.</p>

<!-- </div> --><!-- end of question_frame -->


In [47]:
# 將影像矩陣擴展至9x11，以便應用8x8濾波器且不會超出邊界
padded_img = np.pad(img, ((4, 4), (4, 4)), mode='constant', constant_values=0)

# 定義8x8的水平盒狀濾波器
filter_size = 8
# box_filter = np.ones((filter_size, filter_size))

box_filter = np.array([[1,1,1,1,1,1,1,1],
                       [1,1,1,1,1,1,1,1],
                       [1,1,1,1,1,1,1,1],
                       [1,1,1,1,1,1,1,1],
                       [0,0,0,0,0,0,0,0],
                       [0,0,0,0,0,0,0,0],
                       [0,0,0,0,0,0,0,0],
                       [0,0,0,0,0,0,0,0]])

# 計算 (4, 4) 位置應用濾波器的輸出
x, y = 4, 4  # 偏移位置
output_value = np.sum(padded_img[x:x + filter_size, y:y + filter_size] * box_filter)

print("水平盒狀濾波器輸出值:", output_value)
print(padded_img)
print(box_filter)

水平盒狀濾波器輸出值: 4185
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 122 142 242  57 203 232  30   0   0   0   0]
 [  0   0   0   0 141   5  79 106 138  65 230   0   0   0   0]
 [  0   0   0   0  34 149 203 129 141  34 240   0   0   0   0]
 [  0   0   0   0 214 220 243 150 250 140 246   0   0   0   0]
 [  0   0   0   0 252   9 154  68 239  26  10   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]]
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
